services:
  backend:
    container_name: 'php83-apache2'
    build:
      context: .
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    name: php83_apache2_network
